### ISSUE TITLE
CreateSessionRequest and CreateSessionResponse don't use message header / chunking mechanism

### ISSUE THREAD

**Issue by mmguero** [cisagov/icsnpp-opcua-binary#4]
Attached is a PCAP file raising two exceptions for frame numbers 10 and 13 which cause protocol violations.

After the protocol violations no more OPC UA Logs are generated.

It looks like the OPC UA Parser is expecting an OPC UA Message Header in each frame.

This is not always true. In the attached PCAP, you can see an OPC UA CreateSessionRequest (frame number 9 and 10) with a message size of 1578 Bytes.

The same problem can be observed for the CreateSessionResponse Message (frame number, 12, 13, 14, 17, 18, 23, 26, 27, 30) with a message size of 133900 Bytes.

In both cases, the chunking mechanism of OPC UA is not used (Chunk Type: F).

PS: There is an "unusal" tcp handshake at the beginning of the PCAP causing a “possible_split_routing” message. This is an artefact from our environment, but it has no effect on the described problem.

[opcua.pcap.zip](https://github.com/cisagov/icsnpp-opcua-binary/files/8410127/opcua.pcap.zip)

**Comment by kkvarfordt** [comment]
The initial implementation of the parser used a `binpac datagram flow` definition which results in faster parsing, but does not support incremental input or buffering.  Given the OPC UA data in the provided pcap has data fragmented over multiple frames, the parser has been updated to use a `binpac flowunit flow` which buffers data when there is not enough to evaluate the record and dispatches data for evaluation when the threshold is reached.

Testing:
Testing of the updated parser revealed an issue with the provided pcap that limited verification of the changes.  The updated parser successfully parsed the `CreateSessionRequest` (frames #9 and #10), but due to a TCP Spurious Retransmission at frame #26, parsing of the `CreateSessionResponse` caused the data to be undelivered (`OPCUA_Binary_Analyzer::Undelivered(uint64_t seq, int len, bool orig)`) which sets the `had_gap` flag.  Once this flag is set, further processing of data is disabled when new streams are delivered (`OPCUA_Binary_Analyzer::DeliverStream(int len, const u_char* data, bool orig)`).

Researching Zeek and TCP Spurious Retransmission turned up Zeek issue #1564 which explained that "Zeek assumes that the traffic that it parses is in the same order as it happened."  See the References section below for further details.  Additionally, reviewing the source code for some of the built-in parsers (RDP, SSH, SSL) showed the same code path when the `had_gap` flag is set.  It appears this behavior is normal for Zeek parsers

In an effort to verify the `CreateSessionResponse` parsing up to frame #26, temporary debug statements were put in place that showed the data being processed and buffered.

Implementation:
Implementing the binpac flowunit flow was not as simple as changing from a datagram reference to a flowunit reference in the opcua_binary.pac code base.  This small change would cause the binpac compiler to issue various errors such as "cannot determine initial buffer length for type", etc.  After much digging and gnashing of teeth, three areas in the binpac definitions were causing the compiler errors.

1. The compiler did not like the `bytestring` definitions of the `msg_type` and `is_final` fields in the `Msg_Header` record.  These fields were changed to be `uint8[3]` and `uint8` which caused additional ripple effects throughout the code base.
2. The `Msg_Header` record required an `&length` definition based on the `msg_size` field from the header.
3. The compiler did not like specifying a `&length` definition on the `OPCUA_Binary_PDU` record.  This record has been removed and the `Msg_Header` record updated to take an `is_orig: bool` parameter.

For more details on the code base changes, see the commit history of the repository.

References:
* https://github.com/zeek/binpac#flow
* https://github.com/cisagov/icsnpp-opcua-binary/blob/main/src/OPCUA_Binary.cc#L83-L88
* https://github.com/cisagov/icsnpp-opcua-binary/blob/main/src/OPCUA_Binary.cc#L60-L63
* https://github.com/zeek/zeek/issues/1564
* https://github.com/cisagov/icsnpp-opcua-binary/blob/main/src/opcua_binary.pac#L32
